apiVersion: v1
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Demo Application</title>
        <link href="styles.css" rel="stylesheet" type="text/css">
      </head>
      <body>
        Hello from KOTS.
        <p>This is text from a user config value: 'please change this value' </p>
        </br>
        This is a hidden value:
        </br>
        <ul>
          <li>Hidden Text: 'ydBmxZ28HOx9yXWd59mjPRs5ssC1vGu2UFHcU09F'</li>
          <li>Hidden Text 2: '3VgMI1d_49GtNuN6umYgAbBM0JhB6vJ166CaNHUb'</li>
        </ul>
      </body>
    </html>
  styles.css: |
    body {
      background-color: rgb(224,224,224);
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 100%;
    }
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: nginx
  labels:
    kots.io/app-slug: nginx
    kots.io/backup: velero
  name: nginx-content
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtSWlRFSTRiMUJrU21saU4zRnhOMnhGVjNOd04xaE5SSE5QT2pKRVdVeENPRzlRWkVwcFlqZHhjVGRzUlZkemNEZFlUVVJ6VHc9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtSWlRFSTRiMUJrU21saU4zRnhOMnhGVjNOd04xaE5SSE5QT2pKRVdVeENPRzlRWkVwcFlqZHhjVGRzUlZkemNEZFlUVVJ6VHc9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: nginx
  creationTimestamp: null
  labels:
    kots.io/app-slug: nginx
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: ajp-io
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtSWlRFSTRiMUJrU21saU4zRnhOMnhGVjNOd04xaE5SSE5QT2pKRVdVeENPRzlRWkVwcFlqZHhjVGRzUlZkemNEZFlUVVJ6VHc9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtSWlRFSTRiMUJrU21saU4zRnhOMnhGVjNOd04xaE5SSE5QT2pKRVdVeENPRzlRWkVwcFlqZHhjVGRzUlZkemNEZFlUVVJ6VHc9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: nginx
  creationTimestamp: null
  labels:
    kots.io/app-slug: nginx
    kots.io/backup: velero
  name: nginx-registry
  namespace: ajp-io
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: nginx
  labels:
    app: example
    component: nginx
    kots.io/app-slug: nginx
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: nginx
  labels:
    app: example
    component: nginx
    kots.io/app-slug: nginx
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: nginx-content
        kots.io/app-slug: nginx
      labels:
        app: example
        component: nginx
        kots.io/app-slug: nginx
        kots.io/backup: velero
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-content
      imagePullSecrets:
      - name: nginx-registry
      volumes:
      - configMap:
          name: nginx-content
        name: nginx-content
